=== pkp/ojs/dbscripts/xml/dtd/xmldata.dtd
<!--
  * xmldata.dtd
  *
  * DTD for database data files.
  * Describes data to be inserted into a database.
  *
  * $Id$
  -->

<!ELEMENT data (table?, sql?)*>
<!ELEMENT table (field_default*, row*)>
	<!ATTLIST table
		name CDATA #REQUIRED>
<!ELEMENT field_default (#PCDATA)>
	<!ATTLIST field_default
		name CDATA #REQUIRED
		null (0|1) #IMPLIED>
<!ELEMENT row (field+)>
<!ELEMENT field (#PCDATA)>
	<!ATTLIST field
		name CDATA #REQUIRED
		null (0|1) #IMPLIED>
<!ELEMENT sql (query|drop|rename)*>
<!ELEMENT query (#PCDATA)>
	<!ATTLIST query
		driver CDATA #IMPLIED>
<!ELEMENT drop EMPTY>
	<!ATTLIST drop
		table CDATA #REQUIRED
		column CDATA #IMPLIED>
<!ELEMENT rename EMPTY>
	<!ATTLIST rename
		table CDATA #REQUIRED
		column CDATA #IMPLIED
		to CDATA #REQUIRED>

=== pkp/ojs/dbscripts/xml/data/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../dtd/xmldata.dtd">

<!--
  * sample.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Sample database data XML file.
  *
  * $Id$
  -->

<data>
	<table name="site">
		<row>
			<field name="title">My Site</field>
			<field name="intro">Welcome to my site.</field>
			<field name="journal_redirect">0</field>
			<field name="about">About my site.</field>
		</row>
	</table>
	
	<table name="journals">
		<row>
			<field name="title">Journal 1</field>
			<field name="path">ojs1</field>
			<field name="seq">1</field>
		</row>
		<row>
			<field name="title">Journal 2</field>
			<field name="path">ojs2</field>
			<field name="seq">2</field>
		</row>
	</table>
	
	<sql>
		<query>UPDATE journals SET seq = journal_id</query>
	</sql>
</data>
