<?xml version="1.0" encoding="UTF-8"?>

<!--
  * scheduledTasks.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Scheduled tasks registry file.
  *
  * This file lists all scheduled tasks to be executed by the system.
  *
  * Note that this functionality requires scheduled task support to be enabled.
  * The degree of granularity supported for the task frequency depends on the
  * frequency the scheduled task script itself is scheduled to run (as
  * configured in cron, for example).
  *
  * Example task:
  *
  * <task class="submission.scheduledTask.ReviewReminderTask">
  * 	<descr>Send reviewer reminder emails, once per hour.</descr>
  * 	<frequency minute="0"/>
  * </task>
  *
  * $Id$
  -->

<!DOCTYPE scheduled_tasks [
	<!--
	  * task - a single task to execute
	  * class: the ScheduledTask class to instantiate and call execute() on
	  * descr: description of the task
	  * frequency: how often the task should be executed
	  * arg: 0 or more arguments to pass in array to the class constructor
	  -->
	<!ELEMENT scheduled_tasks (task+)>
	<!ELEMENT task (descr?,frequency?,arg*)>
		<!ATTLIST task
			class CDATA #REQUIRED>
	<!ELEMENT descr (#PCDATA)>
	<!ELEMENT frequency EMPTY>
		<!--
		  * The frequency settings take similar values as used in
		  * crontab entries
		  * E.g., "1", "2-3", "2-3,5,6", "*/2", "1-6/3", "*", etc.
		  * ("*" is assumed for any values that are omitted)
		  *
		  * The primary difference with crontab entries is that the task
		  * may not be executed at the exact specified time. E.g., if a
		  * task is set to execute at minute 0 of every hour, it will be
		  * executed if it has been more than one hour since the task
		  * was last run, regardless of the minute at the time the
		  * script is actually executed.
		  *
		  * minute: 0-59
		  * hour: 0-23
		  * day: 1-31
		  * month: 1-12
		  * dayofweek: 0-6 (Sunday-Saturday)
		  -->
		<!ATTLIST frequency
			minute CDATA #IMPLIED
			hour CDATA #IMPLIED
			day CDATA #IMPLIED
			month CDATA #IMPLIED
			dayofweek CDATA #IMPLIED>
	<!ELEMENT arg (#PCDATA)>
]>

<scheduled_tasks>
	<task class="tasks.ReviewReminder">
		<descr>Send automated reminders to reviewers to complete their assignments.</descr>
		<frequency hour="0"/>
	</task>
	<task class="tasks.SubscriptionExpiryReminder">
		<descr>Send automated reminders to subscribers regarding their expired/about to expire subscriptions.</descr>
		<frequency hour="0"/>
	</task>
	<task class="tasks.OpenAccessNotification">
		<descr>Send automated email to registered readers that have requested to be notified when an issue becomes open access.</descr>
		<frequency hour="0"/>
	</task>
</scheduled_tasks>
