=== pkp/ojs/help/toc.dtd
<!--
  * toc.dtd
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for help table of contents.
  *
  * $Id$
  -->

<!--
  * toc - help table of contents
  * id: the toc ID
  * locale: the key for the locale of this toc
  * title: the toc title
  * parent_topic: the ID of the topic this toc is under, if applicable
  -->
<!ELEMENT toc (topic*,breadcrumb*)>
	<!ATTLIST toc
		id CDATA #REQUIRED
		locale CDATA #REQUIRED
		title CDATA #REQUIRED
		parent_topic CDATA #IMPLIED>

<!--
  * topic - reference to a topic
  * id: the topic ID
  * title: the title of the topic to appear in the toc
  -->
<!ELEMENT topic EMPTY>
	<!ATTLIST topic
		id CDATA #REQUIRED
		title CDATA #REQUIRED>

<!--
  * breadcrumb - reference to a topic
  * url: the url link
  * title: the breadcrumb title
  -->
<!ELEMENT breadcrumb EMPTY>
	<!ATTLIST breadcrumb
		url CDATA #REQUIRED
		title CDATA #REQUIRED>

=== pkp/ojs/help/fa_IR/editorial/toc/000002.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<!DOCTYPE toc SYSTEM "../../../toc.dtd">
<!--
  * 000002.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * table of contents for Editorial Process - Editor's Role - Submissions
  *
  * $Id$
  --><toc title="ساب میشن ها" parent_topic="editorial/topic/000002" locale="fa_IR" id="editorial/toc/000002" >
  <topic title="نامشخص" id="editorial/topic/000015" />
  <topic title="در دست کارشناسی" id="editorial/topic/000016" />
  <topic title="در دست ویراستاری" id="editorial/topic/000017" />
  <topic title="آرشیو" id="editorial/topic/000018" />
  <breadcrumb title="روند دبیری" url="editorial/topic/000000" />
  <breadcrumb title="نقش سردبیر" url="editorial/topic/000001" />
  <breadcrumb title="ساب میشن ها" url="editorial/topic/000002" />
</toc>

=== pkp/ojs/help/es_ES/journal/toc/000003.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toc SYSTEM "../../../toc.dtd">

<!--
  * 000003.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Tabla de Contenidos de la Administración de la Revista - Roles. 
  *
  * Translated by Juan Arias, Corporación Parque Tecnológico de Mérida: juanarias@ula.ve.
  *
  * $Id$
  -->

<toc id="journal/toc/000003" locale="en_US" title="Roles" parent_topic="journal/topic/000003">
	<topic id="journal/topic/000015" title="Administrador de la Revista" />
	<topic id="journal/topic/000016" title="Editor" />
	<topic id="journal/topic/000017" title="Editor de la Sección" />
	<topic id="journal/topic/000019" title="Corrector de Pruebas" />
	<topic id="journal/topic/000018" title="Editor de Diagramación" />
	<topic id="journal/topic/000020" title="Corrector de Pruebas" />
	<topic id="journal/topic/000021" title="Revisor" />
	<topic id="journal/topic/000022" title="Autor" />
	<topic id="journal/topic/000023" title="Lector" />
	<topic id="journal/topic/000032" title="Administrador de las suscripciones" />

	<breadcrumb url="journal/topic/000000" title="Administrador de la Revista" />
	<breadcrumb url="journal/topic/000003" title="Roles" />
</toc>
