=== pkp/ojs/rt/rt-version.dtd
<!--
  * rt-version.dtd
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for Reading Tools version files.
  *
  * $Id$
  -->

<!--
  * version - RT version container
  * locale: locale key code, e.g. "en_US"
  -->
<!ELEMENT version (version_title,version_description,context*)>
	<!ATTLIST version
		id CDATA #REQUIRED
		locale CDATA #REQUIRED>

<!-- Version information -->
<!ELEMENT version_title (#PCDATA)>
<!ELEMENT version_description (#PCDATA)>


<!--
  * context - Grouping of related searches
  -->
<!ELEMENT context (context_title,context_abbrev,context_description,(cites_context|author_terms|define_terms|geo_terms)?,search*)>

<!-- Context information -->
<!ELEMENT context_title (#PCDATA)>
<!ELEMENT context_abbrev (#PCDATA)>
<!ELEMENT context_description (#PCDATA)>
<!ELEMENT author_terms EMPTY> <!-- If present use authors as default search terms -->
<!ELEMENT define_terms EMPTY> <!-- If present use as the "Define Terms" context -->
<!ELEMENT cites_context EMPTY> <!-- If present use as the "Cited By X" context -->
<!ELEMENT geo_terms EMPTY> <!-- If present use geo context as default search terms -->


<!--
  * search - Search engine descriptor
  -->
<!ELEMENT search (search_title,search_description,url,search_url,search_post?)>

<!-- Search information -->
<!ELEMENT search_title (#PCDATA)>
<!ELEMENT search_description (#PCDATA)>
<!ELEMENT url (#PCDATA)> <!-- The URL of the site -->
<!ELEMENT search_url (#PCDATA)> <!-- The URL to feed search terms into. Appending a search term must make this a valid URL -->
<!ELEMENT search_post (#PCDATA)> <!-- Post parameters in query string format, if applicable -->

=== pkp/ojs/rt/fa_IR/Physics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE version SYSTEM "../rt-version.dtd">
<!--
  * Physics.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Reading Tools version: Physics (en_US)
  *
  * $Id$
  -->
<version id="فیزیک" locale="en_US">
	<version_title>فیزیک</version_title>
	<version_description>ابزار خواندن به خوانندگان کمک می کند  تا از دامنه ی وسیعی از منابع موجود که امکان تفسیر ، قرار گرفتن و ارزیابی را فراهم می کند، استفاده کنند</version_description>
	<context>
		<context_title>وظیفه نویسنده</context_title>
		<context_abbrev>دیگر وظایف</context_abbrev>
		<context_description>Identify other works by the article's author(s) by using OAI engines.</context_description>
		<author_terms/>
		<search>
			<search_title>گوگل اسکولار</search_title>
			<search_description>گوگل اسکولار امکان جستجو های خاص را د ر زمینه ادبیات پژوهشی شامل  مقالات کارشناسی شده ، پایان نامه ها، کتب،،پیش پرینت ها، چکیده ها و گزارش های فنی فراهم می سازد.محتوای این حیطه شامل تعدادی از ناشران و تدوین کنند گان است که گوگل توسط آنها نسازمان یافته است.برای مثال انجمن محاسبه ی ماشین ها، 
IEEE،
سرویس جایگزین کتابخانه جهانی با دسترسی آزاد  و ... .نتیایج مشخص شده ورژن های متفاوتی از شاخه ها، تحلیل گفته ها و مکان کتابخانه را (فقط کتاب های موجود) را نشان می دهد</search_description>
			<url>http://scholar.google.com</url>
			<search_url>http://scholar.google.com/scholar?ie=UTF-8&amp;oe=UTF-8&amp;hl=eng&amp;as_sauthors={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>Intute: Science, Engineering &amp; Technology: اینتیوت، علم مهندسی و فناوری</search_title>
			<search_description>اینتیوت :علم، مهندسی و فناوری سرویسی آزاد و آنلاین است که برای شما امکان دسترسی به بهترین منابع شبکه ای برای آموزش و تحقیق را فراهم می کند، و توسط متخصصین شبکه ارزیابی و انتخاب شده است. اینتیوت علوم فیزیکی، مهندسی، محاسبه، جغرافی،ریاضیات و علم محیط را تحت پوشش قرار می دهد. این پایگاه اطلاعاتی در حال حاضر 33349 مورد دارد.</search_description>
			<url>http://www.intute.ac.uk/sciences/</url>
			<search_url>http://www.intute.ac.uk/sciences/cgi-bin/search.pl?submit.x=0&amp;submit.y=0&amp;submit=Go&amp;limit=0&amp;subject=sciences&amp;term1={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>OAIster (Open Archives Initiative research databases):: آرشیوهای باز جستجوی پایگاههای اطلاعاتی</search_title>
			<search_description>OAIster
پروژه ای است از سرویس های کتابخانه دیجیتال دانشگاه میشیگان، که می تواند جستجویی وسیع از انواع مجموعه ها از موسسات بیشمار را فرهم آورد.این موسسات از منابع دیجیتال خود  ثبتی ایجاد می کنند که که در دسترس است و تیم پروژه آنها را برای خدمات 
OAlSter
جمع آوری و تدوین کرده است</search_description>
			<url>http://oaister.umdl.umich.edu/</url>
			<search_url>http://oaister.umdl.umich.edu/cgi/b/bib/bib-idx?type=boolean&amp;size=10&amp;c=oaister&amp;q1=&amp;rgn1=entire+record&amp;op2=and&amp;q2=&amp;rgn2=entire+record&amp;op3=And&amp;q3=&amp;rgn3=title&amp;op4=And&amp;rgn4=author&amp;op5=And&amp;q5=&amp;rgn5=subject&amp;op6=And&amp;rgn6=norm&amp;q6=all+types&amp;sort=author%2Fcreator&amp;submit2=search&amp;q4={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>DOE Information Bridge:DOE
اینفورمیشن بریج
پل اطلاعات</search_title>
			<search_description>اینفورمیشن بریج (پل اطلاعات) منبعی آزاد برای دسترسی به متن کامل و فهرستهای ثبت شده از تحقیقات و گزارشات پیشرفته در
DOE
(گروه انرژی) در زمینه فیزیک، شیمی، مواد، بیولوژی، علوم زیستی، فن آوری انرژی، مهندسی، علم کامپیوتر و اطلاعات، انرژی قابل تجدید و موضوعات دیگر فراهم می آورد.</search_description>
			<url>http://www.osti.gov/bridge/index.jsp</url>
			<search_url>http://www.osti.gov/bridge/basicsearch.jsp?act=Search&amp;formname=basicsearch.jsp&amp;review=1&amp;SortBy=RELV&amp;SortOrder=DESC&amp;querytype=search&amp;searchFor={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>Public Knowledge Project Open Archives Harvester:پروژه آگاهی عمومی از آرشیو باز 
پابلیک نالج پراجکت اپن آرشیو هاروستر
</search_title>
			<search_description>آرشیو کامل و باز 
PKP
یک سیستم نمایه سازی آزاد از متا دیتا ها می باشد که با پروژه ی آگاهی عمومی از طریق کوشش های انجام شده توسط فدرال گسترش یافته تا دسترسی به جستجو را وسیع تر و بهتر سازد. 
منابع اطلاعاتی 
PKP OAI
به شما این امکان را می دهد تا یک نمایه ی قابل جستجو از متا دیتا  ها را از آرشیو های باز و کامل اولیه مانندسایت های مورد استفاده در سیستم مجلات باز یا سیستم های کنفرانس باز ایجاد کنید</search_description>
			<url>http://pkp.sfu.ca/harvester/</url>
			<search_url>http://pkp.sfu.ca/harvester/search.php?limit=author&amp;query={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>Fermilab Preprint Server:سرور پیش پرینت 
Fermilab
،ماشین جستجو
</search_title>
			<search_description>سرور پیش پرینت 
Fermilab
،ماشین جستجو
آرشیوی قابل جستجو از پیش پرینت ها از سال 1972 را نگهداری می کند. متن کامل پیش پرینت ها از سال 1995 تا کنون نیز هم اکنون در دسترس می باشند.</search_description>
			<url>http://fnalpubs.fnal.gov/preprints.html</url>
			<search_url>http://www-spires.fnal.gov/spires/find/hep/wwwscan?subfile=wwwhepau&amp;submit=Browse&amp;rawcmd={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>GrayLIT Network: شبکه 
GrayLIT
</search_title>
			<search_description>شبکه 
GrayLIT
جستجوی متن کامل را از بین ادبیات قدیمی آژانس های چندگانه ی دولتی از طریق یک پرتال علمی با گزارش های فنی امکان پذیر می سازد. این پرتال به آرامی به ماشین های جستجوی مجموعه ادبیات قدیمی متصل می شود و استفاده کننده را قادر می سازد تا اطلاعات را بدون شناختن آژانس حامی پیدا کند.</search_description>
			<url>http://graylit.osti.gov/</url>
			<search_url>http://graylit.osti.gov/cgi-bin/dexplcgi</search_url>
			<search_post>pp=all&amp;INTERFACE=1WINDOW&amp;FORM=DistributedSearch.html&amp;COLLECTION=dticft&amp;COLLECTION=jpl&amp;COLLECTION=gpoinfo&amp;COLLECTION=langley&amp;MAXDOCS=50&amp;QUERY={$formKeywords}</search_post>
		</search>
		<search>
			<search_title>NASA Technical Reports Server:سرور گزارش های فنی 
NASA
</search_title>
			<search_description>سرور گزارش های فنی 
NASA
به کاربران اجازه می دهد که اسناد آنلاین و منتشر شده توسط 
NASA
را که در دسترس هستند را جستجو کنند این اسناد شامل برگزاری جلسات، مقالات مجلات، کنفرانس های در راه، و گزارش های فنی می شود. بسیاری از اسناد این اسناد به شکل 
PostScript
و
PDF
در دسترس می باشند. همه ی اسناد دسته بندی شده نیستند و برای عموم آزاد هستند.</search_description>
			<url>http://ntrs.nasa.gov/index.jsp?method=aboutntrs</url>
			<search_url>http://ntrs.nasa.gov/search.jsp?N=0&amp;Ntk=all&amp;Ntx=mode%20matchall&amp;Ntt={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>CiteSeer</search_title>
			<search_description>CiteSeer
دسترسی به پایگاه اطلاعاتی مقالات تحقیقی خارجی و کاملا نمایه شده را از فیلدهای علمی متفاوت کامپیوتر امکان پذیر می سازد.</search_description>
			<url>http://citeseer.ist.psu.edu/cs</url>
			<search_url>http://citeseer.ist.psu.edu/cs?submit=Search+Documents&amp;cs=1&amp;q={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>SPIRES</search_title>
			<search_description>SPIRES
جستجوی بیش از 450000 مقالات مرتبط به فیزیک انرژی قوی را که شامل مقالات مجله، پیش پرینت ها، 
e-prints
گزارش های فنی، مقالات کنفرانس و پایان نامه ها، می باشد را امکان پذیر می سازد.</search_description>
			<url>http://www.slac.stanford.edu/spires/hep/</url>
			<search_url>http://www.slac.stanford.edu/spires/find/hep/www?TITLE=&amp;C=&amp;REPORT-NUM=&amp;AFFILIATION=&amp;cn=&amp;k=&amp;cc=&amp;eprint=+&amp;eprint=&amp;topcit=&amp;url=&amp;J=+&amp;*=&amp;ps=+&amp;DATE=&amp;*=+&amp;FORMAT=WWW&amp;SEQUENCE=&amp;AUTHOR={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>HighWire</search_title>
			<search_description>های وایر یکی از فشرده ترین مجلات در زمینه علم، تکنولوژی و پزشکی است. از مارس 2002 های وایر حاوی 11785877 مقاله در بیش از 4500 مجله مدلاین(پزشکی) و 405985 مقاله با موضوع آزاد از 321 مجله های وایر است.</search_description>
			<url>http://highwire.stanford.edu/</url>
			<search_url>http://highwire.stanford.edu/cgi/searchresults?andorexactfulltext=and&amp;resourcetype=1&amp;src=hw&amp;fulltext=&amp;pubdate_year=&amp;volume=&amp;firstpage=&amp;disp_type=&amp;author1={$formKeywords}</search_url>
		</search>
	</context>
	<context>
		<context_title>جستجوی واژه ها</context_title>
		<context_abbrev>جستجوی واژه ها</context_abbrev>
		<context_description>روی هر واژه در متن دبل کلیک کنید به صورت نقل قول؛ تعریف واژه ها و نقل قول یا جعبه ظاهر خواهد شد.همچنین می توانید کلمه مورد نظر را در جعبه تایپ یا پیست کنید. سپس از دستور العمل جستجو برای یافتن تعریفی مشخص برای آن کلمه استفاده کنید. این منابع به خاطر ارتباطشان و دسترسی آزاد به همه یا بخشی از مطالبشان انتخاب شده اند</context_description>
		<define_terms/>
		<search>
			<search_title>گوگل</search_title>
			<search_description>با استفاده از ماشین معروف جستجوی گوگل،تعاریف را جستجو کنید</search_description>
			<url>http://www.google.com/</url>
			<search_url>http://www.google.com/search?hl=en&amp;q=define%3A{$formKeywords}</search_url>
		</search>
		<search>
			<search_title>Eric Weisstein's World of Physics</search_title>
			<search_description>دایره المعارف آنلاین از واژگان و فرمول های فیزیک می باشد. بطور کامل قابل جستجو است و به صورت حروف الفبا و یا با عنوان قابل بروز کردن است. بخشی از 
Eric's Treasure Troves
می باشد.</search_description>
			<url>http://scienceworld.wolfram.com/physics/</url>
			<search_url>http://scienceworld.wolfram.com/search/?q={$formKeywords}</search_url>
		</search>
		<search>
			<search_title>Merriam-Webster Online:لغتنامه آن لاین مریام – وبستر</search_title>
			<search_description>این لغتنامه بر اساس دهمین چاپ دانشگاهی وبستر،1993است همراه با بیش از160000 لغت به روز که در هر چاپ سالانه اضافه می شود هر کلمه با تعریف، تلفظ، استفاده، ساختار گرامری و یک تاریخچه کوتاه شامل یک فرهنگ جامع، املای غلط و املاهای پیشنهادی می باشد. سیستم جستجوی فرهنگ لغت جستجوهای غیر قابل پیش بینی و ناقص را فراهم می کند. همچنین راهنمای خوبی برای تلفظ و فایل های صداهای آن تلفظ برای بسیاری از واژه ها می باشد.</search_description>
