<?xml version="1.0" encoding="UTF-8"?>
<!--
  * version.xml
  *
  * Copyright (c) 2005 The Public Knowledge Project
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * OJS version information.
  *
  * $Id$
  -->

<!DOCTYPE version [
	<!ELEMENT version (application, release, tag, date, info, package, patch+)>
	<!ELEMENT application (#PCDATA)>
	<!ELEMENT release (#PCDATA)>
	<!ELEMENT tag (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT info (#PCDATA)>
	<!ELEMENT package (#PCDATA)>
	<!ELEMENT patch (#PCDATA)>
		<!ATTLIST patch
			from CDATA #REQUIRED>
]>

<version>
	<application>ojs2</application>
	<release>2.0.2.1</release>
	<tag>ojs-2_0_2-1</tag>
	<date>2005-09-21</date>
	<info>http://pkp.sfu.ca/ojs/</info>
	<package>http://pkp.sfu.ca/ojs/download/ojs-2.0.2-1.tar.gz</package>
	<patch from="2.0.0.0">http://pkp.sfu.ca/ojs/download/patch/ojs-2.0_to_2.0.2-1.patch.gz</patch>
	<patch from="2.0.1.0">http://pkp.sfu.ca/ojs/download/patch/ojs-2.0.1_to_2.0.2-1.patch.gz</patch>
	<patch from="2.0.2.0">http://pkp.sfu.ca/ojs/download/patch/ojs-2.0.2_to_2.0.2-1.patch.gz</patch>
</version>
