=== pkp/ojs/locale/locale.dtd
<!--
  * locale.dtd
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for localization string definitions.
  *
  * $Id$
  -->

<!--
  * locale - container for localization strings for a specific locale
  * name: the key name associated with the locale
  * full_name: human-readable name of the locale
  -->
<!ELEMENT locale (message*)>
	<!ATTLIST locale
		name CDATA #REQUIRED
		full_name CDATA #IMPLIED>

<!--
  * message - a localized string
  * key: the unique key associated with the string, in the form "sectionname(.subsectionname)*.name"
  * value is the localized string (HTML encoded if necessary). Variables can be specified in the form "{$name}" which will be substituted with the associated parameter when the string is translated
  -->
<!ELEMENT message (#PCDATA)>
	<!ATTLIST message
		key CDATA #REQUIRED>

=== pkp/ojs/plugins/importexport/pubmed/locale/en_US/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/importexport/pubmed/locale/en_US/locale.xml
  *
  * Copyright (c) 2014-2018 Simon Fraser University
  * Copyright (c) 2003-2018 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  * Localization information: https://pkp.sfu.ca/wiki/index.php?title=Translating_OxS
  * Localization strings.
  -->
 
<locale name="en_US" full_name="U.S. English">
	<message key="plugins.importexport.pubmed.displayName">PubMed XML Export Plugin</message>
	<message key="plugins.importexport.pubmed.description">Export article metadata in PubMed XML format for indexing in MEDLINE.</message>
	
	<message key="plugins.importexport.pubmed.export">Export Data</message>
	<message key="plugins.importexport.pubmed.export.issues">Export Issues</message>
	<message key="plugins.importexport.pubmed.export.selectIssue">Select an Issue to export.</message>
	<message key="plugins.importexport.pubmed.export.articles">Export Articles</message>
	<message key="plugins.importexport.pubmed.export.selectArticle">Select Articles to export.</message>
	
	<message key="plugins.importexport.pubmed.cliUsage"><![CDATA[Usage: 
{$scriptName} {$pluginName} [xmlFileName] [journal_path] articles [articleId1] [articleId2] ...
{$scriptName} {$pluginName} [xmlFileName] [journal_path] issue [issueId]
]]></message>
	<message key="plugins.importexport.pubmed.cliError">ERROR:</message>

	<message key="plugins.importexport.pubmed.export.error.issueNotFound">No issue matched the specified issue ID "{$issueId}".</message>
	<message key="plugins.importexport.pubmed.export.error.articleNotFound">No article matched the specified article ID "{$articleId}".</message>


</locale>

=== pkp/ojs/plugins/auth/ldap/locale/pt_BR/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../locale/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * LDAP authentication plugin localization strings for the pt_BR locale.
  *
  * $Id$
  -->
 
<locale name="pt_BR" full_name="Português do Brasil">
	<message key="plugins.auth.ldap.displayName">LDAP</message>
	<message key="plugins.auth.ldap.description">Plugin de Autenticação LDAP.</message>
	
	<message key="plugins.auth.ldap.settings">Configurações LDAP</message>
	<message key="plugins.auth.ldap.settings.hostname">Servidor</message>
	<message key="plugins.auth.ldap.settings.hostname.description">Ex.: "ldap.example.com", ou "ldaps://ldap.example.com" (para uso com SSL)</message>
	<message key="plugins.auth.ldap.settings.port">Porta</message>
	<message key="plugins.auth.ldap.settings.port.description">Opcional. Valor padrão é 389 (LDAP) ou 636 (LDAP sobre SSL)</message>
	<message key="plugins.auth.ldap.settings.basedn">Base DN</message>
	<message key="plugins.auth.ldap.settings.basedn.description">Ex.: "ou=people,dc=example,dc=com"</message>
	<message key="plugins.auth.ldap.settings.managerdn">Gerente DN</message>
	<message key="plugins.auth.ldap.settings.managerdn.description">Ex.: "cn=Manager,dc=example,dc=com"</message>
	<message key="plugins.auth.ldap.settings.managerpwd">Senha</message>
	<message key="plugins.auth.ldap.settings.managerpwd.description">O Gerente DN e a Senha são obrigatórios apenas quando se utiliza a sincronização de cadastro/senha ou as opções de criação de usuário são habilitadas. Caso o LDAP seja usado apenas para autenticação, estas opções podem ser ignoradas.</message>
	<message key="plugins.auth.ldap.settings.pwhash">Criptografia da Senha</message>
	<message key="plugins.auth.ldap.settings.pwhash.description"><![CDATA[Formato de criptografia para senhas armazenadas no servidor. SHA1 recomendado (requer PHP >= 4.3.0).]]></message>
	<message key="plugins.auth.ldap.settings.saslopt">Configurações SASL (opcional)</message>
	<message key="plugins.auth.ldap.settings.sasl"><![CDATA[Utilizar SASL ao invés de autenticação simples(requer PHP >= 5)]]></message>
	<message key="plugins.auth.ldap.settings.saslmech">Mecanismo SASL</message>
	<message key="plugins.auth.ldap.settings.saslmech.description">Ex.: "DIGEST-MD5"</message>
	<message key="plugins.auth.ldap.settings.saslrealm">Domínio</message>
	<message key="plugins.auth.ldap.settings.saslauthzid">ID de Autorização Solicitado</message>
	<message key="plugins.auth.ldap.settings.saslprop">Propriedades de Segurança SASL</message>
	<message key="plugins.auth.ldap.settings.uid">Atributo de nome de conta</message>
	<message key="plugins.auth.ldap.settings.uid.description">O atributo cujo valor identifica de forma única um objeto usuário, como um uid ou cn ou sAMAccountName.</message>
</locale>

=== pkp/ojs/plugins/pubIds/urn/locale/en_US/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/pubIds/urn/locale/en_US/locale.xml
  *
  * Copyright (c) 2014-2019 Simon Fraser University
  * Copyright (c) 2003-2019 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  * Localization information: https://pkp.sfu.ca/wiki/index.php?title=Translating_OxS
  * Localization strings.
  -->

<locale name="en_US" full_name="U.S. English">
	<message key="plugins.pubIds.urn.displayName">URN</message>
	<message key="plugins.pubIds.urn.description">This plugin enables the assignment of the Uniform Resource Names to the issues, articles and galleys in OJS.</message>

	<!-- settings form -->
	<message key="plugins.pubIds.urn.manager.settings.description">Please configure the URN plugin to be able to manage and use URNs in OJS:</message>

	<message key="plugins.pubIds.urn.manager.settings.urnObjects">Journal Content</message>
	<message key="plugins.pubIds.urn.manager.settings.urnObjectsRequired">Please choose the objects URNs should be assigned to.</message>
	<message key="plugins.pubIds.urn.manager.settings.explainURNs">Please select the publishing objects that will have Uniform Resource Names (URN) assigned:</message>
	<message key="plugins.pubIds.urn.manager.settings.enableIssueURN">Issues</message>
	<message key="plugins.pubIds.urn.manager.settings.enableSubmissionURN">Articles</message>
	<message key="plugins.pubIds.urn.manager.settings.enableRepresentationURN">Galleys</message>

	<message key="plugins.pubIds.urn.manager.settings.urnPrefix">URN Prefix</message>
	<message key="plugins.pubIds.urn.manager.settings.urnPrefix.description"><![CDATA[The URN prefix is the fix, never changing part of the URN (e.g. "urn:nbn:de:0000-").]]></message>
	<message key="plugins.pubIds.urn.manager.settings.form.urnPrefixPattern"><![CDATA[The URN prefix pattern must be in the form "urn:"&lt;NID&gt;":"&lt;NSS&gt;.]]></message>

	<message key="plugins.pubIds.urn.manager.settings.urnSuffix">URN Suffix</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffix.description">A URN suffix can take any form, but must be unique among all publishing objects with the same URN prefix assigned:</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixPattern">Use the pattern entered below to generate URN suffixes. Use %j for journal initials, %v for the volume number, %i for the issue number, %Y for the year, %a for the OJS article ID, %g for the OJS galley ID, %f for the OJS file ID, %p for the page number and %x for "Custom Identifier".</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixPattern.example">For example, vol%viss%ipp%p could create the URN suffix "vol3iss2pp230".</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixPattern.issues">for issues</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixPattern.submissions">for articles</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixPattern.representations">for galleys</message>
	<message key="plugins.pubIds.urn.manager.settings.urnIssueSuffixPatternRequired">Please enter the URN suffix pattern for issues.</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSubmissionSuffixPatternRequired">Please enter the URN suffix pattern for articles.</message>
	<message key="plugins.pubIds.urn.manager.settings.urnRepresentationSuffixPatternRequired">Please enter the URN suffix pattern for galleys.</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixDefault">Use default patterns.</message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixDefault.description"><![CDATA[%j.v%vi%i for issues<br />%j.v%vi%i.%a for articles<br />%j.v%vi%i.%a.g%g for galleys.]]></message>
	<message key="plugins.pubIds.urn.manager.settings.urnSuffixCustomIdentifier">Enter an individual URN suffix for each published item. You'll find an additional URN input field on each item's metadata page.</message>
	<message key="plugins.pubIds.urn.manager.settings.checkNo">Check Number</message>
	<message key="plugins.pubIds.urn.manager.settings.checkNo.label">The check number will be automatically calculated and added at the end, as the last digit of an URN.</message>
	<message key="plugins.pubIds.urn.manager.settings.namespace">Namespace</message>
	<message key="plugins.pubIds.urn.manager.settings.namespace.choose">Choose</message>
	<message key="plugins.pubIds.urn.manager.settings.namespace.description">The persistent identifier namespace usually needed for the registration (e.g. at the Deutsche Nationalbibliothek).</message>
	<message key="plugins.pubIds.urn.manager.settings.urnResolver">Resolver URL</message>
	<message key="plugins.pubIds.urn.manager.settings.urnResolver.description">(e.g. http://nbn-resolving.de/)</message>
	<message key="plugins.pubIds.urn.manager.settings.form.urnResolverRequired">Please enter the resolver URL.</message>

	<message key="plugins.pubIds.urn.manager.settings.urnReassign">Reassign URNs</message>
	<message key="plugins.pubIds.urn.manager.settings.urnReassign.description">If you change your URN configuration, URNs that have already been assigned will not be affected. Once the URN configuration is saved, use this button to clear all existing URNs so that the new settings will take effect with existing objects.</message>
	<message key="plugins.pubIds.urn.manager.settings.urnReassign.confirm">Are you sure you wish to delete all existing URNs?</message>

	<!-- metadata form -->
	<message key="plugins.pubIds.urn.editor.urn">URN</message>
	<message key="plugins.pubIds.urn.editor.urnObjectTypeIssue">issue</message>
	<message key="plugins.pubIds.urn.editor.urnObjectTypeSubmission">article</message>
	<message key="plugins.pubIds.urn.editor.urnObjectTypeRepresentation">galley</message>
	<message key="plugins.pubIds.urn.editor.customSuffixMissing">The URN cannot be assigned because the custom suffix is missing.</message>
	<message key="plugins.pubIds.urn.editor.patternNotResolved">The URN cannot be assigned because it contains an unresolved pattern.</message>
	<message key="plugins.pubIds.urn.editor.canBeAssigned">What you see is a preview of the URN. Select the checkbox and save the form to assign the URN.</message>
	<message key="plugins.pubIds.urn.editor.assigned">The URN is assigned to this {$pubObjectType}.</message>
	<message key="plugins.pubIds.urn.editor.urnSuffixCustomIdentifierNotUnique">The given URN suffix is already in use for another published item. Please enter a unique URN suffix for each item.</message>
	<message key="plugins.pubIds.urn.editor.clearObjectsURN">Clear URN</message>
	<message key="plugins.pubIds.urn.editor.clearObjectsURN.confirm">Are you sure you wish to delete the existing URN?</message>
	<message key="plugins.pubIds.urn.editor.clearIssueObjectsURN">Clear Issue Objects URNs</message>
	<message key="plugins.pubIds.urn.editor.clearIssueObjectsURN.confirm">Are you sure you wish to delete the existing issue objects URNs?</message>
	<message key="plugins.pubIds.urn.editor.clearIssueObjectsURN.description">Use the following option to clear URNs of all objects (articles and galleys) currently scheduled for this issue.</message>
	<message key="plugins.pubIds.urn.editor.addCheckNo">Add Check Number</message>
	<!-- assignment form -->
	<message key="plugins.pubIds.urn.editor.assignURN">Assign the URN {$pubId} to this {$pubObjectType}</message>
	<message key="plugins.pubIds.urn.editor.assignURN.emptySuffix">The URN cannot be assigned because the custom suffix is missing.</message>
	<message key="plugins.pubIds.urn.editor.assignURN.pattern">The URN {$pubId} cannot be assigned because it contains an unresolved pattern.</message>
	<message key="plugins.pubIds.urn.editor.assignURN.assigned">The URN {$pubId} has been assigned.</message>
	<!-- errors -->
	<message key="plugins.pubIds.urn.form.checkNoRequired">The check number is missing.</message>

</locale>

=== pkp/ojs/plugins/citationFormats/abnt/locale/pt_PT/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/citationFormats/abnt/locale/pt_PT/locale.xml
  *
  * Copyright (c) 2013-2014 Simon Fraser University Library
  * Copyright (c) 2003-2014 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for this citation plugin in pt_PT.
  *
  -->
 
<locale name="pt_PT" full_name="Português">
	<message key="plugins.citationFormats.abnt.displayName">Plugin Formato de Citação ABNT</message>
	<message key="plugins.citationFormats.abnt.citationFormatName">ABNT</message>
	<message key="plugins.citationFormats.abnt.description">Este plugin implementa o formato de citação ABNT.</message>
	
	<message key="plugins.citationFormats.abnt.manager.settings">Configurações</message>
	<message key="plugins.citationFormats.abnt.manager.AbntCitationSettings">Configurações do formato de citação ABNT</message>
	<message key="plugins.citationFormats.abnt.manager.settings.description">Configurações de campos usados para referências segundo formato ABNT.</message>
	<message key="plugins.citationFormats.abnt.manager.settings.location">Local</message>
	
	
	<message key="plugins.citationFormats.abnt.retrieved"><![CDATA[Disponível em: &lt;<a href="{$url}" target="_new">{$url}</a>&gt;. Acesso em: {$retrievedDate}.]]></message>
</locale>

=== pkp/ojs/plugins/auth/ldap/locale/uk_UA/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/auth/ldap/locale/uk_UA/locale.xml
  *
  * Copyright (c) 2014-2019 Simon Fraser University
  * Copyright (c) 2003-2019 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * LDAP authentication plugin localization strings for the uk_UA (Українська) locale.
  *
  * Translated by Denys Solovianenko, 2011
  * V. I. Vernadsky National Library of Ukraine
  -->
 
<locale name="uk_UA" full_name="Українська">
       <message key="plugins.auth.ldap.displayName">LDAP</message>
       <message key="plugins.auth.ldap.description">Цей модуль дозволяє аутентифікацію та синхронізацію облікових записів користувачів засобами зовнішніх джерел даних LDAP.</message>
       
       <message key="plugins.auth.ldap.settings">Налаштування LDAP</message>
       <message key="plugins.auth.ldap.settings.hostname">Ім'я хоста серверу</message>
       <message key="plugins.auth.ldap.settings.hostname.description">наприклад, "ldap.example.com" або "ldaps://ldap.example.com" (для використання SSL)</message>
       <message key="plugins.auth.ldap.settings.port">Порт серверу</message>
       <message key="plugins.auth.ldap.settings.port.description">Необов'язкове. За замовчуванням 389 (LDAP) або 636 (LDAP через SSL)</message>
       <message key="plugins.auth.ldap.settings.basedn">База DN</message>
       <message key="plugins.auth.ldap.settings.basedn.description">наприклад, "ou=people,dc=example,dc=com"</message>
       <message key="plugins.auth.ldap.settings.managerdn">DN менеджера</message>
       <message key="plugins.auth.ldap.settings.managerdn.description">наприклад, "cn=Manager,dc=example,dc=com"</message>
       <message key="plugins.auth.ldap.settings.managerpwd">Пароль менеджера</message>
       <message key="plugins.auth.ldap.settings.managerpwd.description">DN та пароль менеджера необхідні лише у випадку, якщо дозволена синхронізація профіля/пароля користувача або опції створення користувача. Якщо LDAP буде використовуватися виключно для аутентифікації, ці опції можуть бути опущені.</message>
       <message key="plugins.auth.ldap.settings.uid">Атрибут імені облікового запису</message>
       <message key="plugins.auth.ldap.settings.uid.description">Атрибут, який унікально ідентифікує користувача як об'єкт, наприклад, uid, cn або sAMAccountName.</message>
       <message key="plugins.auth.ldap.settings.pwhash">Шифрування пароля</message>
       <message key="plugins.auth.ldap.settings.saslopt">Налаштування SASL (необов'язкове)</message>
       <message key="plugins.auth.ldap.settings.saslmech">Механізм SASL</message>
       <message key="plugins.auth.ldap.settings.saslmech.description">наприклад, "DIGEST-MD5"</message>
       <message key="plugins.auth.ldap.settings.saslrealm">Realm</message>
       <message key="plugins.auth.ldap.settings.saslauthzid">Неохідний authorization ID</message>
       <message key="plugins.auth.ldap.settings.saslprop">Параметри безпеки SASL</message>
</locale>

=== pkp/ojs/plugins/generic/customLocale/locale/el_GR/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../locale/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the en_US (U.S. English) locale.
  *
  * $Id$
  -->
 
<locale name="en_US" full_name="U.S. English">
	<message key="plugins.generic.customLocale.name">Plugin προσαρμογής τοπικών ρυθμίσεων</message>
	<message key="plugins.generic.customLocale.description">Το plugin αυτό ενεργοποιεί την δυνατότητα προσαρμογής του κειμένου της εξ'ορισμού διεπαφής του χρήστη που χρησιμοποιεί το OJS.</message>

	<message key="plugins.generic.customLocale.longDescription">Αυτή η σελίδα εμφανίζει όλες τις τρέχουσες τοπικές ρυθμίσεις που είναι εγκατεστημένες για αυτό το περιοδικό.</message>
	<message key="plugins.generic.customLocale.localeDescription">Αυτή η σελίδα εμφανίζει όλα τα διαθέσιμα αρχεία για την επιλεγμένη τοπική ρύθμιση.</message>
	<message key="plugins.generic.customLocale.fileDescription">Εισάγετε το κείμενό σας στο αντίστοιχο πεδίο προσαρμογής κειμένου. Αφήστε το πεδίο κενό αν επιθυμείτε να χρησιμοποιήσετε το εξ'ορισμού κείμενο του OJS.</message>
	<message key="plugins.generic.customLocale.localeName">Όνομα τοπικής ρύθμισης</message>
	<message key="plugins.generic.customLocale.localeKey">Κλειδί</message>
	<message key="plugins.generic.customLocale.localeKey.description">Εισάγετε ένα ολόκληρο κλειδί τοπικής ρύθμισης για να την αναζητήσετε.</message>
	<message key="plugins.generic.customLocale.localeKeyValue">Τιμή</message>
	<message key="plugins.generic.customLocale.customize">Προσαρμογή</message>
	<message key="plugins.generic.customLocale.availableLocales">Διαθέσιμες τοπικές ρυθμίσεις</message>

	<message key="plugins.generic.customLocale.locale">{$locale} Τοπική Ρύθμιση</message>
	<message key="plugins.generic.customLocale.localeFiles">Τοπικές Ρυθμίσεις</message>
	<message key="plugins.generic.customLocale.file.filename">Όνομα αρχείου</message>
	<message key="plugins.generic.customLocale.file.edit">Επεξεργασία {$filename}</message>
	<message key="plugins.generic.customLocale.file.reference">Εξ'ορισμού κείμενο</message>
	<message key="plugins.generic.customLocale.file.custom">Προσαρμοσμένο κείμενο</message>
</locale>

=== pkp/ojs/plugins/generic/browse/locale/ru_RU/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/browse/locale/ru_RU/locale.xml
  *
  * Copyright (c) 2014-2016 Simon Fraser University Library
  * Copyright (c) 2003-2016 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Browse plugin localization strings
  -->
 
<locale name="ru_RU" full_name="Русский">
	<!-- plugin -->
	<message key="plugins.generic.browse.displayName">Просмотр</message>
	<message key="plugins.generic.browse.description">Этот модуль позволяет просмотр по разделам и/или идентификационным типам.</message>

	<!-- URN manager options, setting -->
	<message key="plugins.generic.browse.manager.settings">Настройки</message>
	<message key="plugins.generic.browse.manager.settings.description">Пожалуйста, установите следующие дополнительные инструменты просмотра:</message>

	<message key="plugins.generic.browse.manager.settings.browseSettings">Настройки просмотра</message>
	<message key="plugins.generic.browse.manager.settings.browse">Просмотр</message>
	<message key="plugins.generic.browse.manager.settings.browseByObjects">Виберите объекты, по которым можно будет осуществлять просмотр.</message>
	<message key="plugins.generic.browse.manager.settings.enableBrowseBySections">По разделам</message>
	<message key="plugins.generic.browse.manager.settings.enableBrowseByIdentifyTypes">По идентификационным типам</message>
	<message key="plugins.generic.browse.manager.settings.excludedSections">Исключенные разделы</message>
	<message key="plugins.generic.browse.manager.settings.excludedSections.description">Виберите разделы, которые не следует включать в просмотр.</message>
	<message key="plugins.generic.browse.manager.settings.excludedIdentifyTypes">Исключенные идентификационные типы</message>
	<message key="plugins.generic.browse.manager.settings.excludedIdentifyTypes.description">Виберите идентификационные типы, которые не следует включать в просмотр.</message>

	<message key="plugins.generic.browse.search.sections">По разделам</message>
	<message key="plugins.generic.browse.search.sectionIndex">Просмотр списка разделов</message>
	<message key="plugins.generic.browse.search.sectionDetails">Информация о разделе</message>
	<message key="plugins.generic.browse.search.identifyTypes">По идентификационным типам</message>
	<message key="plugins.generic.browse.search.identifyTypeIndex">Просмотр списка идентификационных типов</message>
	<message key="plugins.generic.browse.search.identifyTypeDetails">Информация об идентификационном типе</message>

</locale>

=== pkp/ojs/plugins/importexport/mets/locale/cs_CZ/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../locale/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the en_US (U.S. English) locale.
  *
  * $Id$
  -->
 
<locale name="en_US" full_name="U.S. English">
	<message key="plugins.importexport.METSExport.displayName">Plugin pro export METS XML</message>
	<message key="plugins.importexport.METSExport.description">Export časopisů do METS XML</message>
	<message key="plugins.importexport.METSExport.settings">Nastavení</message>
	<message key="plugins.importexport.METSExport.export">Export dat</message>
	<message key="plugins.importexport.METSExport.export.issues">Export čísel</message>
	<message key="plugins.importexport.METSExport.export.selectIssue">Vybrat čísla pro export.</message>
	<message key="plugins.importexport.METSExport.export.error.IssuesNotFound">Žádné číslo neodpovídá uvedenému ID čísla "{$issueId}".</message>
	<message key="plugins.importexport.METSExport.export.error.unknownIssue">Neznámá cesta {$journalPath}</message>
	<message key="plugins.importexport.METSExport.settings.FContent">Použít base64 encoding pro balič obsahu</message>
	<message key="plugins.importexport.METSExport.settings.FLocat">Použít URL bitstreamu pro balič obsahu</message>
	<message key="plugins.importexport.METSExport.settings.organization">METS:agent element organization attribute</message>
	<message key="plugins.importexport.METSExport.settings.preservationLevel">Úroveň zachování PREMIS</message>
	<message key="plugins.importexport.METSExport.settings.exportSuppFiles">Export doplňkových souborů</message>
</locale>
