=== pkp/ojs/locale/locale.dtd
<!--
  * locale.dtd
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for localization string definitions.
  *
  * $Id$
  -->

<!--
  * locale - container for localization strings for a specific locale
  * name: the key name associated with the locale
  * full_name: human-readable name of the locale
  -->
<!ELEMENT locale (message*)>
	<!ATTLIST locale
		name CDATA #REQUIRED
		full_name CDATA #IMPLIED>

<!--
  * message - a localized string
  * key: the unique key associated with the string, in the form "sectionname(.subsectionname)*.name"
  * value is the localized string (HTML encoded if necessary). Variables can be specified in the form "{$name}" which will be substituted with the associated parameter when the string is translated
  -->
<!ELEMENT message (#PCDATA)>
	<!ATTLIST message
		key CDATA #REQUIRED>

=== pkp/ojs/plugins/generic/customLocale/locale/vi_VN/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../locale/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the en_US (U.S. English) locale.
  *
  * $Id$
  -->
 
<locale name="en_US" full_name="U.S. English">
	<message key="plugins.generic.customLocale.name">Công cụ phụ trợ ngôn ngữ tùy biến</message>
	<message key="plugins.generic.customLocale.description">Công cụ này cho phép tùy biến ngôn ngữ giao diện người dụng mặc định trên phần mềm OJS.</message>

	<message key="plugins.generic.customLocale.longDescription">Trang này liệt kê tất cả các ngôn ngữ hiện được cài đặt cho tạp chí này.</message>
	<message key="plugins.generic.customLocale.localeDescription">Trang này liệt kê tất cả các file sẵn có cho ngôn ngữ được chọn.</message>
	<message key="plugins.generic.customLocale.fileDescription">Nhập từ ngữ vào ô chữ tùy biến tương ứng. Để trống ô chữ tùy biến nếu muốn sử dụng từ ngữ mặc định của OJS.</message>
	<message key="plugins.generic.customLocale.localeName">Tên ngôn ngữ</message>
	<message key="plugins.generic.customLocale.localeKey">Nút chữ</message>
	<message key="plugins.generic.customLocale.localeKeyValue">Giá trị</message>
	<message key="plugins.generic.customLocale.customize">Tùy biến</message>
	<message key="plugins.generic.customLocale.availableLocales">Các ngôn ngữ hiện có</message>

	<message key="plugins.generic.customLocale.locale">{$locale} Ngôn ngữ</message>
	<message key="plugins.generic.customLocale.localeFiles">Các file ngôn ngữ</message>
	<message key="plugins.generic.customLocale.file.filename">Tên file</message>
	<message key="plugins.generic.customLocale.file.edit">Sửa {$filename}</message>
	<message key="plugins.generic.customLocale.file.reference">Từ ngữ mặc định</message>
	<message key="plugins.generic.customLocale.file.custom">Từ ngữ tùy biến</message>
</locale>

=== pkp/ojs/plugins/generic/announcementFeed/locale/nb_NO/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/announcementFeed/locale/nb_NO/locale.xml
  *
  * Copyright (c) 2014-2018 Simon Fraser University
  * Copyright (c) 2003-2018 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the nb_NO (Norsk bokmål) locale.
  *
  -->
 
<locale name="nb_NO" full_name="Norsk bokmål">
	<message key="plugins.generic.announcementfeed.displayName">Programutvidelse for feed av Kunngjøringer.</message>
	<message key="plugins.generic.announcementfeed.description">Denne programutvidelsen produserer RSS/Atom feed av tidsskriftets Kunngjøringer.</message>

	<message key="plugins.generic.announcementfeed.settings">Innstillinger</message>
	<message key="plugins.generic.announcementfeed.settings.all">Vis feed-lenker på alle tidsskriftsider.</message>
	<message key="plugins.generic.announcementfeed.settings.homepage">Vis feed-lenker bare på hjemmesiden og kunngjøringssiden.</message>
	<message key="plugins.generic.announcementfeed.settings.announcement">Vis feed-lenker bare på kunngjøringssiden.</message>
	<message key="plugins.generic.announcementfeed.settings.recentAnnouncements1">Begrens feeden til</message>
	<message key="plugins.generic.announcementfeed.settings.recentAnnouncements2">nyeste kunngjøringer.</message>
	<message key="plugins.generic.announcementfeed.settings.recentItemsRequired">Vennligst oppgi et tall for hvor mange av de nyeste kunngjøringene som skal vises.</message>
	<message key="plugins.generic.announcementfeed.atom.altText">Atom logo</message>
	<message key="plugins.generic.announcementfeed.rss1.altText">RSS1 logo</message>
	<message key="plugins.generic.announcementfeed.rss2.altText">RSS2 logo</message>
</locale>

=== pkp/ojs/plugins/generic/thesisFeed/locale/fa_IR/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../locale/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the en_US (U.S. English) locale.
  *
  * $Id$
  -->
 
<locale name="en_US" full_name="U.S. English">
	<message key="plugins.generic.thesisfeed.displayName">پلاکین فید چکیده پایان نامه</message>
	<message key="plugins.generic.thesisfeed.description">این پلاگین فید سندیکائی آر اس اس - اتم برای چکیده پایان نام ها ایجاد میکند</message>

	<message key="plugins.generic.thesisfeed.settings">تنظیمات</message>
	<message key="plugins.generic.thesisfeed.settings.all">نمایش لینک فید در تمام صفحات سایت مجله</message>
	<message key="plugins.generic.thesisfeed.settings.homepage">نمایش لینک فید فقط در صفحه خانگی و صفحه چکیده پایان نامه ها</message>
	<message key="plugins.generic.thesisfeed.settings.thesis">نمایش لینک فید فقط در صفحه چکیده پایان نامه ها</message>
	<message key="plugins.generic.thesisfeed.settings.recentThesis1">فید محدود باشد به</message>
	<message key="plugins.generic.thesisfeed.settings.recentThesis2">چکیده های پایان نامه اخیرا ارسال شده.</message>
	<message key="plugins.generic.thesisfeed.settings.recentItemsRequired">تعداد چکیده های پایان نامه را به صورت عدد صحیح مثبتی وارد کنید.</message>
	<message key="plugins.generic.thesisfeed.atom.altText">لوگوی اتم</message>
	<message key="plugins.generic.thesisfeed.rss1.altText">لوگوی آر اس اس ۱</message>
	<message key="plugins.generic.thesisfeed.rss2.altText">لوگوی آر اس اس ۲</message>
</locale>

=== pkp/ojs/plugins/importexport/crossref/locale/fr_CA/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../locale/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the fr_CA locale.
  *
  * $Id$
  -->
 
<locale name="fr_CA" full_name="Français (Canada)">
	<message key="plugins.importexport.crossref.displayName">Plugiciel d'exportation CrossRef XML</message>
	<message key="plugins.importexport.crossref.description">Exporter les métadonnées de l'article en format CrossRef XML.</message>
	
	<message key="plugins.importexport.crossref.export">Exporter des données</message>
	<message key="plugins.importexport.crossref.export.issues">Exporter des numéros</message>
	<message key="plugins.importexport.crossref.export.selectIssue">Sélectionner un numéro à exporter</message>
	<message key="plugins.importexport.crossref.export.articles">Exporter des articles</message>
	<message key="plugins.importexport.crossref.export.selectArticle">Sélectionner des articles à exporter</message>
	
	<message key="plugins.importexport.crossref.cliUsage">Utilisation : 
{$scriptName} {$pluginName} [xmlFileName] [journal_path] articles [articleId1] [articleId2] ...
{$scriptName} {$pluginName} [xmlFileName] [journal_path] numéro [issueId]</message>
	<message key="plugins.importexport.crossref.cliError">ERREUR :</message>

	<message key="plugins.importexport.crossref.export.error.issueNotFound">Aucun numéro ne correspond à l'identification de numéro spécifié "{$issueId}".</message>
	<message key="plugins.importexport.crossref.export.error.articleNotFound">Aucun article ne correspond à l'identification d'article spécifié "{$articleId}".</message>

	<message key="plugins.importexport.crossref.errors.noDOIprefix">Il faut spécifier un préfixe DOI valide dans la configuration de la revue afin d'utiliser ce plugiciel.</message>
</locale>

=== pkp/ojs/locale/fr_CA/submission.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../lib/pkp/dtd/locale.dtd">

<!--
  * locale/fr_CA/submission.xml
  *
  * Copyright (c) 2014-2019 Simon Fraser University
  * Copyright (c) 2003-2019 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  * Localization information: https://pkp.sfu.ca/wiki/index.php?title=OJS:_French_(fr_CA)
  * Localization strings.
  -->

<locale name="fr_CA" full_name="Français (Canada)">
	<!-- Submission wizard -->

	<!-- Submission Information Modal -->

	<!-- events -->

	<!-- galleys grid -->

	<!-- galley files grid -->
	<message key="submission.submit.form.authorRequiredFields">Les prénom, nom et adresse courriel de chaque auteur sont requis.</message>
	<message key="submission.submit.form.titleRequired">Inscrire le titre de votre article.</message>
	<message key="submission.submit.form.abstractRequired">Inscrire le résumé de votre article.</message>
	<message key="submission.submit.form.contributorRoleRequired">Sélectionner le rôle du contributeur.</message>
	<message key="submission.citationFormat.notFound">Le format de citation n'a pas été repéré.</message>
	<message key="submission.metadataDescription">Ces spécifications sont basées sur l'ensemble d'éléments de métadonnées de Dublin Core, une norme internationale utilisée pour décrire les contenus d'une revue.</message>
	<message key="submission.incomplete">En attente d'approbation</message>
	<message key="submission.submit.form.localeRequired">Sélectionner une langue pour la soumission</message>
	<message key="submission.submit.submissionChecklist">Liste de vérification de la soumission</message>
	<message key="submission.submit.submissionChecklistDescription">Lire et cocher les éléments suivants pour indiquer que vous répondez aux exigences.</message>
	<message key="submission.submit.privacyStatement">Déclaration de confidentialité</message>
	<message key="submission.submit.contributorRole">Rôle du contributeur</message>
	<message key="submission.submit.form.authorRequired">Au moins un auteur est requis.</message>
	<message key="submission.submit.title">Soumettre un article</message>
	<message key="submission.submit.userGroup">Rôle</message>
	<message key="submission.submit.userGroupDescription">Choisissez le rôle sous lequel vous soumettez votre article.</message>
	<message key="submission.upload.selectComponent">Sélectionner l'élément de l'article</message>
	<message key="submission.title">Titre de l'article</message>
	<message key="submission.title.tip">voici une variable avec une valeur erronée</message>
	<message key="submission.submit.newSubmissionMultiple">Commencer une nouvelle soumission dans</message>
	<message key="submission.submit.newSubmissionSingle">Nouvelle soumission</message>
	<message key="grid.action.workflow">Processus éditorial pour la soumission</message>
	<message key="submission.issueEntry">Métadonnées</message>
	<message key="submission.submit.whatNext.description">La revue a été informée de votre soumission et vous a envoyé par courriel une confirmation pour vos dossiers.  Un rédacteur communiquera avec vous lorsque votre soumission aura été examinée.</message>
	<message key="editor.submission.decision.sendExternalReview">Envoyer en évaluation</message>
	<message key="submission.event.issueMetadataUpdated">Les métadonnées pour la publication de la soumission ont été mises à jour.</message>
	<message key="submission.upload.fileContents">Élément de l'article</message>
	<message key="submission.complete">Approuvé</message>
	<message key="grid.action.issueEntry">Voir les métadonnées de la soumission</message>
	<message key="submission.issueEntry.modalTitle">Métadonnées de la soumission et de la publication</message>
	<message key="submission.issueEntry.submissionMetadata">Soumission</message>
	<message key="submission.issueEntry.publicationMetadata">Publication</message>
	<message key="submission.issueEntry.confirm">Assigner l'article à un numéro en vous basant sur les métadonnées ci-dessous.</message>
	<message key="grid.action.galleyInIssueEntry">Les épreuves se trouvent dans le dossier du numéro.</message>
	<message key="submission.event.articleGalleyMadeAvailable">L'article mis en page "{$galleyFormatName}" est disponible.</message>
	<message key="submission.event.articleGalleyMadeUnavailable">L'article mis en page "{$galleyFormatName}" n'est pas disponible.</message>
	<message key="submission.event.publicIdentifiers">Identifiants publics mis à jour.</message>
	<message key="grid.issueEntry.availableGalley.title">Approbation du format</message>
	<message key="grid.issueEntry.availableGalley.removeMessage"><![CDATA[<p>Ce mod`èle de mise en page <em>ne sera plus offert</em>aux lecteurs</p>.]]></message>
	<message key="grid.issueEntry.availableGalley.message"><![CDATA[<p>Ce mod`èle de mise en page <em>sera offert</em>aux lecteurs</p>.]]></message>
	<message key="grid.action.availableArticleGalley">Rendre ce modèle de mise en page disponible</message>
	<message key="submission.galleyFiles">Fichiers de mise en page</message>
	<message key="submission.proofReadingDescription"><![CDATA[Le responsable de la mise en page télécharge les fichiers qui ont été préparés pour publication ici.  Utiliser <em>Assigner un vérificateur</em> pour identifier les auteurs et les autres personnes qui reliront les articles mis en page, avec les fichiers corrigés téléchargés, pour approbation avant la publication.]]></message>
	<message key="grid.action.approveProof">Approuver cette épreuve.</message>
	<message key="grid.action.pageProofApproved">Cette épreuve a été approuvée.</message>
	<message key="submission.submit.titleAndSummary">Titre et résumé</message>
	<message key="submission.submit.upload.description">Télécharger les fichier associés à la soumission, incluant l'article, les fichiers multimedia, les ensembles de données, les oeuvres d'art, etc.</message>
	<message key="submission.pageProofs">Correction d'épreuve</message>
	<message key="submission.confirmSubmit">Êtes-vous certain de vouloir soumettre cet article à la revue?</message>
	<message key="workflow.review.externalReview">Évaluation</message>
	<message key="submission.abstract.wordCount.description">Le résumé doit contenir {$wordCount} mots ou moins.</message>
	<message key="submission.submit.form.wordCountAlert">Votre résumé est trop long. Veuillez le raccourcir selon la limite indiquée.</message>
	<message key="section.any">Aucune rubrique</message>
</locale>

=== pkp/ojs/plugins/importexport/crossref/locale/el_GR/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../locale/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the Greek locale.
  *
  * Translation by University of Patras, Library & Information Service
  * Vassilis Barkayannis (barkayannis@upatras.gr),
  * Panos Georgiou (panos@lis.upatras.gr),
  * Giannis Tsakonas (john@lis.upatras.gr),
  * Kiriazis Vasilis (vaskir@lis.upatras.gr),
  * Papaxristopoulos Leonidas (leonidasp@lis.upatras.gr)
  *
  * $Id$
  -->
 
<locale name="el_GR" full_name="Greek">	
	<message key="plugins.importexport.crossref.displayName">Plugin εξαγωγής CrossRef XML </message>
	<message key="plugins.importexport.crossref.description">Εξαγωγή των μεταδεδομένων του άρθρου σε μορφή CrossRef XML .</message>
	
	<message key="plugins.importexport.crossref.export">Εξαγωγή δεδομένων</message>
	<message key="plugins.importexport.crossref.export.issues">Εξαγωγή Τευχών</message>
	<message key="plugins.importexport.crossref.export.selectIssue">Επιλέξτε ένα τεύχος για εξαγωγή.</message>
	<message key="plugins.importexport.crossref.export.articles">Εξαγωγή Άρθρων</message>
	<message key="plugins.importexport.crossref.export.selectArticle">Επιλέξτε ένα άρθρο για εξαγωγή.</message>
	
	<message key="plugins.importexport.crossref.cliUsage"><![CDATA[Usage: 
{$scriptName} {$pluginName} [xmlFileName] [journal_path] articles [articleId1] [articleId2] ...
{$scriptName} {$pluginName} [xmlFileName] [journal_path] issue [issueId]
]]></message>
	<message key="plugins.importexport.crossref.cliError">ΣΦΑΛΜΑ:</message>

	<message key="plugins.importexport.crossref.export.error.issueNotFound">Δεν βρέθηκε τεύχος που να ταιριάζει με το συγκεκριμένο ID τεύχους "{$issueId}".</message>
	<message key="plugins.importexport.crossref.export.error.articleNotFound">Δεν βρέθηκε άρθρο που να ταιριάζει με το συγκεκριμένο ID άρθρου "{$articleId}".</message>

	<message key="plugins.importexport.crossref.errors.noDOIprefix">Ένα έγκυρο πρόθημα DOI (DOI Prefix) πρέπει να καθοριστεί στην Οργάνωση του Περιοδικού ώστε να μπορέσετε να χρησιμοποιήσετε αυτό το plugin.</message>
</locale>

=== pkp/ojs/plugins/paymethod/paypal/locale/cs_CZ/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/paymethod/paypal/locale/cs_CZ/locale.xml
  *
  * Copyright (c) 2013-2014 Simon Fraser University Library
  * Copyright (c) 2006-2009 Gunther Eysenbach, Juan Pablo Alperin, MJ Suhonos
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the cs_CZ (Czech) locale.
  -->
 
<locale name="cs_CZ" full_name="Czech">
	<message key="plugins.paymethod.paypal.displayName">Platba poplatku přes PayPal</message>

	<!-- PayPal Settings Form -->
	<message key="plugins.paymethod.paypal.settings.paypalenable">Povolit PayPal</message>
	<message key="plugins.paymethod.paypal.settings.paypalurl">IPN URL</message>
	<message key="plugins.paymethod.paypal.settings.paypalurl.description"><![CDATA[Toto je URL na službu PayPal - Instant Payment Notification (IPN). Pro testování použijte <u>https://www.sandbox.paypal.com/cgi-bin/webscr</u>; pro produkční systémy použijte <u>https://www.paypal.com/cgi-bin/webscr</u>.]]></message>
	<message key="plugins.paymethod.paypal.settings.selleraccount">Účet prodejce</message>
	<message key="plugins.paymethod.paypal.settings.selleraccount.description">Toto je uživatelské jméno PayPal účtu prodejce, který se má použít - obvykle emailová adresa. Ujistěte se, že máte aktivován Instant Payment Notification (IPN) ve vašem profilu účtu prodejce.</message>
	<message key="plugins.paymethod.paypal.settings.curlNotInstalled">Varování: CURL podpora pro PHP není nainstalována. Podpora PayPal plateb vyžaduje knihovnu CURL a nebude fungovat, dokud nebude nainstalována.</message>
	<message key="plugins.paymethod.paypal.settings">PayPal nastavení</message>

	<!-- PayPal -->
	<message key="plugins.paymethod.paypal">Platba poplatku přes PayPal</message>
	<message key="plugins.paymethod.paypal.description"><![CDATA[PayPal umožňuje uživatelům, ať už jsou nebo nejsou členy PayPal, použít všechny běžné typy platebních karet. Manažer bude muset nastavit <a href="http://www.paypal.com" target="_new">PayPal Business Account</a>.]]></message>
	<message key="plugins.paymethod.paypal.warning">Klikněte na tlačítko Continue níže pro přechod na stránku PayPal, kde můžete použít platební karty pro zaplacení poplatku (bez nutnosti stát se členem PayPal). Po provedení platby použijte tlačítko "Return to Merchant" pro návrat na tuto stránku.</message>
	<message key="plugins.paymethod.paypal.purchase.title">Název</message>
	<message key="plugins.paymethod.paypal.purchase.fee">Poplatek</message>
	<message key="plugins.paymethod.paypal.purchase.description">Popis</message>
	<message key="plugins.paymethod.paypal.purchase.cancelled">Váš nákup byl zrušen.</message>
	<message key="plugins.paymethod.paypal.purchase.cancelled.title">Nákup zrušen</message>
</locale>

=== pkp/ojs/plugins/generic/customBlockManager/locale/it_IT/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2008 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the en_US (U.S. English) locale.
  *
  * $Id: locale.xml,v 1.3 2009/10/17 18:32:10 rcy Exp $
  -->
 
<locale name="en_US" full_name="U.S. English">
	<message key="plugins.generic.customBlockManager.displayName">Gestore di blocchi personalizzati</message>
	<message key="plugins.generic.customBlockManager.description">Questo plugin permette di gestire blocchi personalizzati sulle barre laterali. E' possibile modificare i blocchi nelle impostazioni di ciascun plugin creato.</message>	
	<message key="plugin.generic.customBlockManager.introduction"><![CDATA[Si può utilizzare il plugin per aggiungere o cancellare plugin di blocchi personalizzati. Puoi successivamente modificare il contenuto dei plugin  tramite la pagina <a href="{$systemPluginsUrl}">Plugin</a> (nella sezione Plugin per i blocchi).  Per definire la posizione in cui comparirà il plugin, utilizza il <a href="{$setupStep56}">punto 5.6 del Setup</a>]]></message>
	<message key="plugins.generic.customBlockManager.settings">Impostazioni</message>
	<message key="plugins.generic.customBlockManager.description">This Plugin lets you manage custom sidebar blocks.  You can edit the blocks in the settings of each plugin that you create here.</message>
	<message key="plugins.generic.customBlockManager.blockName">Nome del blocco</message>	
	<message key="plugins.generic.customBlockManager.action">Azione</message>	
	<message key="plugins.generic.customBlockManager.delete">Cancella</message>	
	<message key="plugins.generic.customBlockManager.addBlock">Aggiungi un blocco</message>	

	<message key="plugins.generic.customBlock.content">Contenuto</message>
	<message key="plugins.generic.customBlock.saved"><![CDATA[Il contenuto del blocco &#232; stato salvato.]]></message>
	<message key="plugins.generic.customBlock.nameSuffix">(Plugin del blocco personalizzato)</message>
	<message key="plugins.generic.customBlock.description"><![CDATA[Questo blocco &#232; generato dall'utente.]]></message>
	<message key="plugins.generic.customBlock.editContent">Modifica il contenuto della barra laterale</message>
	<message key="plugins.generic.customBlock.contentRequired"><![CDATA[Inserisci del contenuto. Se vuoi puoi cancellare questo blocco, attraverso il plugin Gestore di blocchi personalizzati o nascondendolo nel punto <a href="{$setupStep56}">punto 5.6 del Setup</a>]]></message>
	<message key="plugins.generic.customBlock.edit">Modifica</message>
</locale>
