=== pkp/ojs/locale/locale.dtd
<!--
  * locale.dtd
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for localization string definitions.
  *
  * $Id$
  -->

<!--
  * locale - container for localization strings for a specific locale
  * name: the key name associated with the locale
  * full_name: human-readable name of the locale
  -->
<!ELEMENT locale (message*)>
	<!ATTLIST locale
		name CDATA #REQUIRED
		full_name CDATA #IMPLIED>

<!--
  * message - a localized string
  * key: the unique key associated with the string, in the form "sectionname(.subsectionname)*.name"
  * value is the localized string (HTML encoded if necessary). Variables can be specified in the form "{$name}" which will be substituted with the associated parameter when the string is translated
  -->
<!ELEMENT message (#PCDATA)>
	<!ATTLIST message
		key CDATA #REQUIRED>

=== pkp/ojs/plugins/generic/webFeed/locale/tr_TR/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * locale.xml
  *
  * Copyright (c) 2003-2012 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the tr_TR (Turkish) locale.
  *
  * $Id$
  -->
 
<locale name="tr_TR" full_name = "Turkish">
	<message key="plugins.generic.webfeed.displayName">Web Feed Plugin</message>
	<message key="plugins.generic.webfeed.description">This plugin produces RSS/Atom web syndication feeds for the current issue.</message>

	<message key="plugins.generic.webfeed.settings">Settings</message>
	<message key="plugins.generic.webfeed.settings.issue">Display web feed links on issue pages only.</message>
	<message key="plugins.generic.webfeed.settings.homepage">Display web feed links on homepage and issue pages only.</message>
	<message key="plugins.generic.webfeed.settings.all">Display web feed links on all journal pages.</message>

	<message key="plugins.generic.webfeed.settings.currentIssue">Display items in current published issue.</message>
	<message key="plugins.generic.webfeed.settings.recentArticles">most recent published items.</message>
	<message key="plugins.generic.webfeed.settings.recentItemsRequired">Please enter a positive integer for recent published items.</message>
	<message key="plugins.generic.webfeed.atom.altText">Atom logo</message>
	<message key="plugins.generic.webfeed.rss1.altText">RSS1 logo</message>
	<message key="plugins.generic.webfeed.rss2.altText">RSS2 logo</message>
</locale>

=== pkp/ojs/plugins/generic/counter/locale/zh_CN/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/counter/locale/zh_CN/locale.xml
  *
  * Copyright (c) 2014-2016 Simon Fraser University Library
  * Copyright (c) 2003-2016 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the zh_CN (简体中文) locale.
  *
  -->
 
<locale name="zh_CN" full_name="简体中文">
	<message key="plugins.generic.counter.description"><![CDATA[计数器插件提供关于站点活动的记录和<a href="http://www.projectcounter.org/about.html" target="_new">计数</a>报告.]]></message>
	<message key="plugins.generic.counter">计数器统计</message>
	<message key="plugins.generic.counter.migrate">日志文件迁移</message>
	<message key="plugins.generic.counter.1a.title">期刊报告1(R2): 按月份与杂志的全文文章点击请求</message>
	<message key="plugins.generic.counter.1a.title1">期刊报告1(R2)</message>
	<message key="plugins.generic.counter.1a.title2">按照月份与期刊的全文请求成功次数( {$year})</message>
	<message key="plugins.generic.counter.1a.dateRun">日运行:</message>
	<message key="plugins.generic.counter.1a.publisher">Publisher</message>
	<message key="plugins.generic.counter.1a.platform">平台</message>
	<message key="plugins.generic.counter.1a.printIssn">ISSN</message>
	<message key="plugins.generic.counter.1a.onlineIssn">在线ISSN</message>
	<message key="plugins.generic.counter.1a.ytdTotal">YTD Total</message>
	<message key="plugins.generic.counter.1a.ytdHtml">YTD HTML</message>
	<message key="plugins.generic.counter.1a.ytdPdf">YTD PDF</message>
	<message key="plugins.generic.counter.1a.totalForAllJournals">总计所有期刊</message>
</locale>

=== pkp/ojs/plugins/generic/customBlockManager/locale/cs_CZ/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/customBlockManager/locale/cs_CZ/locale.xml
  *
  * Copyright (c) 2013-2014 Simon Fraser University Library
  * Copyright (c) 2003-2014 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the cs_CZ locale.
  *
  -->
 
<locale name="cs_CZ" full_name="Czech">
	<message key="plugins.generic.customBlockManager.displayName">Manažer uživatelských panelů</message>
	<message key="plugin.generic.customBlockManager.introduction"><![CDATA[Můžete použít tento plugin pro přidání nebo smazání pluginů uživatelských panelů. Potom můžete editovat obsah prostřednictvím stránky <a href="{$systemPluginsUrl}">Systémových pluginů</a> (v sekci panelových pluginů).  Pro umístění vašeho pluginu na požadované místo v postraním panelu, přejděte ke  <a href="{$setupStep56}">Kroku 5.6</a>]]></message>
	<message key="plugins.generic.customBlockManager.settings">Nastavení</message>
	<message key="plugins.generic.customBlockManager.blockName">Název panelu</message>	
	<message key="plugins.generic.customBlockManager.action">Akce</message>	
	<message key="plugins.generic.customBlockManager.delete">Smazat</message>	
	<message key="plugins.generic.customBlockManager.addBlock">Přidat panel</message>	

	<message key="plugins.generic.customBlock.content">Obsah</message>
	<message key="plugins.generic.customBlock.saved">Obsah panelu byl uložen.</message>
	<message key="plugins.generic.customBlock.nameSuffix">(Plugin uživatelských panelů)</message>
	<message key="plugins.generic.customBlock.description">Toto je uživatelem vytvořený panel.</message>
	<message key="plugins.generic.customBlock.editContent">Editovat obsah postranního panelu</message>
	<message key="plugins.generic.customBlock.contentRequired">Je vyžadován nějaký obsah. Pokud si přejete smazat tento panel, můžete tak udělat pomocí pluginu Manažer panelů nebo srušením výběru tohoto panelu v Kroku 5 v nastavení časopisu.</message>
	<message key="plugins.generic.customBlock.edit">Editovat</message>
</locale>

=== pkp/ojs/plugins/generic/webFeed/locale/fi_FI/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/webFeed/locale/fi_FI/locale.xml
  *
  * Copyright (c) 2014-2019 Simon Fraser University
  * Copyright (c) 2003-2019 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  * Localization information: https://pkp.sfu.ca/wiki/index.php?title=Translating_OxS
  * Localization strings.
  -->
 
<locale name="fi_FI" full_name="Suomi">
	<message key="plugins.generic.webfeed.displayName">Verkkosyötelisäosa</message>
	<message key="plugins.generic.webfeed.description">Tämä lisäosa tuottaa RSS/Atom-verkkosisältösyötteitä uusimmalle numerolle.</message>

	<message key="plugins.generic.webfeed.settings">Asetukset</message>
	<message key="plugins.generic.webfeed.settings.issue">Näytä verkkosyötelinkit vain numeroiden sivuilla.</message>
	<message key="plugins.generic.webfeed.settings.homepage">Näytä verkkosyötelinkit vain etusivulla ja numeroiden sivuilla.</message>
	<message key="plugins.generic.webfeed.settings.all">Näytä verkkosyötelinkit julkaisun kaikilla sivuilla.</message>

	<message key="plugins.generic.webfeed.settings.currentIssue">Näytä kohteet uusimmassa julkaistussa numerossa.</message>
	<message key="plugins.generic.webfeed.settings.recent">Näytä kiinteä määrä viimeisimpiä kohteita.</message>
	<message key="plugins.generic.webfeed.settings.recentArticles">Näytettävien kohteiden määrä</message>
	<message key="plugins.generic.webfeed.settings.recentItemsRequired">Anna positiivinen kokonaisluku viimeisimmille julkaistuille kohteille.</message>
	<message key="plugins.generic.webfeed.atom.altText">Atom-logo</message>
	<message key="plugins.generic.webfeed.rss1.altText">RSS1-logo</message>
	<message key="plugins.generic.webfeed.rss2.altText">RSS2-logo</message>
</locale>

=== pkp/ojs/plugins/generic/openAds/locale/ro_RO/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/openAds/locale/ro_RO/locale.xml
  *
  * Copyright (c) 2013-2014 Simon Fraser University Library
  * Copyright (c) 2003-2013 Siavash Miri and Alec Smecher
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the ro_RO (Română) locale.
  * KOSSON FECIT
  -->
 
<locale name="ro_RO" full_name="Română">
	<message key="plugins.generic.openads.description">Modulul OpenAds permite introducerea de anunţuri comerciale de la serverul OpenAds pentru a fi introduse în OJS.</message>
	<message key="plugins.generic.openads.descriptionUnconfigured"><![CDATA[Modulul OpenAds permite introducerea de anunţuri comerciale de la serverul OpenAds pentru a fi introduse în OJS. <strong>Citiţi fişierul README din plugins/generic/openAds pentru informare la activarea acestui modul.</strong>]]></message>
	<message key="plugins.generic.openads">Modulul OpenAds</message>
	<message key="plugins.generic.openads.settings.description">Folosiţi acest formular pentru a selecta zonele OpenAds care vor fi afişate în OJS pentru fiecare locaţie posibilă.</message>
	<message key="plugins.generic.openads.manager.settings">Setări</message>
	<message key="plugins.generic.openads.error.missingParameter">Cel puţin unul dintre parametrii de configurare al OpenAds nu a putut fi citit din fişierul de configurare. Parametrii ceruţi sunt dbhost, dbuser, dbpassword, dbname, url_prefix, şi table_prefix.</message>
	<message key="plugins.generic.openads.error.dbConnectionError">Nu m-am putut conecta la baza de date OpenAds.</message>

	<message key="plugins.generic.openads.headerAd">Header Ad</message>
	<message key="plugins.generic.openads.contentAd">Content Ad</message>
	<message key="plugins.generic.openads.sidebarAd">Sidebar Ad</message>

	<message key="plugins.generic.openads.orientation.left">Stânga</message>
	<message key="plugins.generic.openads.orientation.centre">Centru</message>
	<message key="plugins.generic.openads.orientation.right">Dreapta</message>
	<message key="plugins.generic.openads.error.configFileNotFound">Fișierul de configurare {$filename} nu a putut fi accesat.</message>
</locale>

=== pkp/ojs/plugins/generic/customLocale/locale/pt_PT/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/customLocale/locale/pt_PT/locale.xml
  *
  * Copyright (c) 2013-2015 Simon Fraser University Library
  * Copyright (c) 2003-2015 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the pt_PT (Português) locale.
  *
  -->
 
<locale name="pt_PT" full_name="Português">
	<message key="plugins.generic.customLocale.name">Plugin de Customização de Idioma</message>
	<message key="plugins.generic.customLocale.description">Este plugin permite a customização do idioma da interface padrão do sistema.</message>

	<message key="plugins.generic.customLocale.longDescription">Esta página lista todos os idiomas actualmente instalados na revista.</message>
	<message key="plugins.generic.customLocale.localeDescription">Esta página lista todos os ficheiros disponíveis para o idioma seleccionado.</message>
	<message key="plugins.generic.customLocale.fileDescription">Indique o texto no campo correspondente. Deixe o campo em branco para utilizar a tradução original.</message>
	<message key="plugins.generic.customLocale.localeName">Título para a tradução</message>
	<message key="plugins.generic.customLocale.localeKey">Chave</message>
	<message key="plugins.generic.customLocale.localeKeyValue">Valor</message>
	<message key="plugins.generic.customLocale.customize">Customizar</message>
	<message key="plugins.generic.customLocale.availableLocales">Idiomas disponíveis</message>

	<message key="plugins.generic.customLocale.locale">Idioma {$locale}</message>
	<message key="plugins.generic.customLocale.localeFiles">Ficheiros de tradução</message>
	<message key="plugins.generic.customLocale.file.filename">Nome do ficheiro</message>
	<message key="plugins.generic.customLocale.file.edit">Editando {$filename}</message>
	<message key="plugins.generic.customLocale.file.reference">Texto original</message>
	<message key="plugins.generic.customLocale.file.custom">Texto customizado</message>
	<message key="plugins.generic.customLocale.localeKey.description">Insira uma chave de tradução completa para pesquisar.</message>
</locale>

=== pkp/ojs/plugins/importexport/medra/locale/fr_CA/common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * @file plugins/importexport/medra/locale/fr_CA/common.xml
  *
  * Copyright (c) 2013-2014 Simon Fraser University Library
  * Copyright (c) 2003-2014 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Shared localization strings
  -->
 
<locale name="fr_CA" full_name="Français (Canada)">
	<message key="plugins.importexport.common.error.DOIsNotAvailable">Afin d'utiliser ce plugiciel, veuillez aller dans la catégorie des "identifiants publics", activez et configurez le plugiciel DOI et spécifiez un préfixe DOI valide.</message>
	<message key="plugins.importexport.common.error.pluginNotConfigured">Ce plugiciel n'est pas entièrement configuré.</message>

	<message key="plugins.importexport.common.settings">Paramètres</message>

	<message key="plugins.importexport.common.settings.form.password">Mot de passe</message>
	<message key="plugins.importexport.common.settings.form.passwordRequired">Veuillez entrer un mot de passe.</message>
	
	<message key="plugins.importexport.common.register">Enregistrer</message>
	<message key="plugins.importexport.common.registerDescription">Veuillez cliquer ce bouton pour enregistrer cet objet à l'agence d'enregistrement pour la première fois. Cela ne fonctionne qu'à condition de n'avoir jamais enregistré cet objet auparavant.</message>
	<message key="plugins.importexport.common.registerDescription.multi">Veuillez cliquer ce bouton pour enregistrer ou mettre à jour les métadonnées d'un objet sélectionné avec l'agence d'enregistrement.</message>
	<message key="plugins.importexport.common.register.error.mdsError">L'enregistrement a échoué! Le serveur d'enregistrement DOI a retourné une erreur: '{$param}'.</message>
	<message key="plugins.importexport.common.register.success">Enregistrement réussi!</message>
	<message key="plugins.importexport.common.register.warning">Enregistrer plusieurs objets peut prendre un moment. Veuillez être patient après avoir cliqué le bouton "Enregistrer". Vous serez averti lorsqu'il sera complété.</message>
	<message key="plugins.importexport.common.register.noCredentials"><![CDATA[L'enregistrement est actuellement désactivé. S'il vous plaît, <a href="{$settingsUrl}">configurez</a> un nom d'utilisateur et un mot de passe afin de pouvoir enregistrer les objets directement  auprès de l'agence.]]></message>

	<message key="plugins.importexport.common.update">Mise à jour</message>
	<message key="plugins.importexport.common.updateDescription">Cliquez ce bouton afin de mettre à jour les métadonnées de l'objet avec l'agence d'enregistrement. Cela ne fonctionne que si vous avez réussi à enregistrer l'objet auparavant.</message>
		
	<message key="plugins.importexport.common.export">Exporter les données</message>
	<message key="plugins.importexport.common.export.unregistered">Exporter tous les numéros, articles et épreuves qui ne sont pas enregistrés</message>
	<message key="plugins.importexport.common.export.selectUnregistered">Sélectionner tous les numéros, articles et épreuves qui ne sont pas enregistrés</message>
	<message key="plugins.importexport.common.export.noUnregistered">Tous les numéros, articles et épreuves ont déjà été enregistrés (ou aucun d'eux n'a de DOI assigné).</message>
	<message key="plugins.importexport.common.export.issues">Exporter un/des numéro(s)</message>
	<message key="plugins.importexport.common.export.selectIssue">Sélectionner des numéros</message>
	<message key="plugins.importexport.common.export.noIssues">Aucun numéro n'a actuellement de DOI assigné.</message>
	<message key="plugins.importexport.common.export.articles">Exporter un/des article(s)</message>
	<message key="plugins.importexport.common.export.selectArticle">Sélectionner des articles</message>
	<message key="plugins.importexport.common.export.noArticles">Aucun article n'a actuellement de DOI assigné.</message>
	<message key="plugins.importexport.common.export.galleys">Exporter une/des épreuve(s)</message>
	<message key="plugins.importexport.common.export.selectGalley">Sélectionner des épreuves</message>
	<message key="plugins.importexport.common.export.noGalleys">Aucune épreuve n'a actuellement de DOI assigné.</message>
	<message key="plugins.importexport.common.exportDescription">Cliquez ce bouton pour exporter les données XML pour le(s) objet(s) sélectionné(s) dans un fichier local sans les enregistrer avec l'agence d'enregistrement. Cela peut être utile si vous désirez qu'un tiers enregistre des DOI pour vous ou si vous voulez inspecter le format XML avant de l'enregistrer.</message>
 
	<message key="plugins.importexport.common.export.error.issueNotFound">Aucun numéro ne correspond à celui indiqué {$param}.</message>
	<message key="plugins.importexport.common.export.error.articleNotFound">Aucun article ne correspond à l'ID de l'article spécifié: {$param}.</message>
	<message key="plugins.importexport.common.export.error.galleyNotFound">Aucune épreuve ne correspond à l'ID de l'épreuve spécifiée: {$param}.</message>
	<message key="plugins.importexport.common.export.error.noDoiAssigned">L'objet dont l'ID est {$param} n'a pas de DOI assigné.</message>
	<message key="plugins.importexport.common.export.error.unknownJournal">Aucune revue ne correspond au chemin spécifié: {$param}.</message>
	<message key="plugins.importexport.common.export.error.unknownObjectType">L'objet de type {$param} ne peut être exporté.</message>
	<message key="plugins.importexport.common.export.error.outputFileNotWritable">Le fichier de sortie {$param} n'est pas accessible en écriture.</message>
 
	<message key="plugins.importexport.common.notification.exportSuccessful">L'objet a été exporté avec succès vers '{$param}'</message>
 
	<message key="plugins.importexport.common.cliError">ERREUR:</message>
	<message key="plugins.importexport.common.markRegistered">Marquer les objets déjà enregistrés</message>
	<message key="plugins.importexport.common.markRegisteredDescription">Cliquez sur ce bouton afin de marquer les objets enregistrés (par exemple, s'ils ont été enregistrés antérieurement ou manuellement).</message>
</locale>

=== pkp/ojs/plugins/reports/counter/locale/eu_ES/locale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale SYSTEM "../../../../../lib/pkp/dtd/locale.dtd">

<!--
  * plugins/generic/counter/locale/eu_ES/locale.xml
  *
  * Copyright (c) 2013-2014 Simon Fraser University Library
  * Copyright (c) 2003-2014 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localization strings for the eu_ES (Basque (Euskara)) locale.
  *
  -->
 
<locale name="eu_ES" full_name="Euskara">
	<message key="plugins.reports.counter.description"><![CDATA[COUNTER pluginak webgunearen jarduera erregistratzen du eta <a href="http://www.projectcounter.org/about.html" target="_new">COUNTER</a> moduko txostena ematen du.]]></message>
	<message key="plugins.reports.counter">COUNTER estatistikak</message>
	<message key="plugins.reports.counter.migrate">Migratu log-fitxategia</message>
	<message key="plugins.reports.counter.1a.title">Aldizkariaren 1. txostena (R2): Testu osoko artikulu-eskaerak hilabetez eta aldizkariz</message>
	<message key="plugins.reports.counter.1a.title1">Aldizkariaren 1. txostena (R2)</message>
	<message key="plugins.reports.counter.1a.title2">Testu osoko artikulu-eskaera zuzenak hilabetez eta egunkariz ({$year} urtea)</message>
	<message key="plugins.reports.counter.1a.dateRun">Data:</message>
	<message key="plugins.reports.counter.1a.publisher">Argitaratzailea</message>
	<message key="plugins.reports.counter.1a.platform">Plataforma</message>
	<message key="plugins.reports.counter.1a.printIssn">Inprimatzeko ISSN</message>
	<message key="plugins.reports.counter.1a.onlineIssn">Lineako ISSN</message>
	<message key="plugins.reports.counter.1a.ytdTotal">Aurten guztira</message>
	<message key="plugins.reports.counter.1a.ytdHtml">HTML</message>
	<message key="plugins.reports.counter.1a.ytdPdf">PDF</message>
	<message key="plugins.reports.counter.1a.totalForAllJournals">Aldizkari guztien totala</message>
</locale>
